### ISSUE TITLE
Homepage | Navigation Bar

### ISSUE THREAD

**Issue by longduongkms** [UEH-Squad/VMS#17]
As a user,

I want UEH logo and Navigation Bar on the top of the wewb page

**Acceptance Criteria**:

1. There is a brand text under the logo."VolunteerMatch"

    Color: blue or green

    Font: Helvetica/URW Geometric/Nunito/Montserrat

2. Main functions on Nav Bar:

    Home

    Go Volunteer 

    Blogs (is not yet named)

    Map

    Notification (shown as icon)

    Account (shown as user avatar)

3. Conceptual color: Blue (#005180); White (#FFFFFF); Green (is not yet chosed)

**Comment by Yen21351** [comment]
Updated:
- Fonts: Montserrat
- Main functions on Nav Bar: Trang chủ, GoVirlunteer, Đơn vị tổ chức, Bản đồ
- Conceptual color: https://docs.google.com/document/d/1hc9Csc0ce8YjyXrStomYkxejMZqIV9z9s-T3JQMBps4/edit#heading=h.94lerme6v4jk
- Mockups: 
+ Desktop:  https://www.figma.com/file/QBd1sOQKIMuqlv88lk2Kni/Website?node-id=0%3A1
+ Mobile:  https://www.figma.com/file/vt0GV8RfYsBE99XXj6vV68/Mobile?node-id=0%3A1
