### ISSUE TITLE
Homepage | Body Part - Opportunities Filter

### ISSUE THREAD

**Issue by Chammmmmm** [UEH-Squad/VMS#22]
As a user,

I want an Opportunities Filter bar right under the main banner
So that I can reach to volunteer activities directly when I access the web page.

**Acceptance Criteria:**
1. There is a big title. "Khám phá hoạt động & chương trình tình nguyện phù hợp với bạn"
- Text color: blue, bold
- Position: center
2. There is a slice bar which contains the filter icons (as design below)
![image](https://user-images.githubusercontent.com/87629993/126694930-c01c41f2-3889-44a4-bae9-e546d5a5cf43.png)
- Icon color: green for background and white for image
- Some initial filters (would be added more in the future): Cộng Đồng, Giáo dục, Sức khỏe, Môi trường, Chuyển Nhà, Thể Thao, Sự Kiện, Khẩn Cấp

**Comment by Yen21351** [comment]
- There are 12 areas in total. Check out at: https://docs.google.com/document/d/1bivwRaQu9hGGnGPs7xuVsbeQfXpbzTL-_MjbNv-JzHQ/edit
- Icon code: update later
