### ISSUE TITLE
Homepage | Body Part - Quote Banner

### ISSUE THREAD

**Issue by Chammmmmm** [UEH-Squad/VMS#24]
As a user,

I want to be aware of the web page's mission by reaching the Quote Banner.

**Acceptance Criteria:**
1. There is a banner which contains quote text as the image below:
- The banner would be added in the future
- The text is designed as a quote (there is no number on the banner as the image below)
![image](https://user-images.githubusercontent.com/87629993/126699536-b10e781f-7125-4a07-9c41-40c63cc229d1.png)

**Comment by Yen21351** [comment]
@hoanguyennph 
- There are 4 remarkable figures: https://docs.google.com/document/d/1kqScQEUk4s2ztxe73qKzwb0E-w8acuI8Ps8JW8AuYy0/edit
- Check out the effect samples at: https://www.alverno.edu/
![image](https://user-images.githubusercontent.com/82808388/127863200-af08bb66-848b-425b-90b0-c43a0b073484.png)
