### ISSUE TITLE
Homepage | The Website Footer

### ISSUE THREAD

**Issue by Chammmmmm** [UEH-Squad/VMS#27]
As a user,

I want to read the privacy policy and organization rules of Go Volunteer website
So that I can be aware of the website using.

**Acceptance Criteria:**
1. The background color of footer is green/gray/blue (choose only one)
![image](https://user-images.githubusercontent.com/87629993/126804636-baef575f-e766-489f-8abe-53132fad15a4.png)

2. The logo of Go Volunteer is on the top left of the footer with big size
3. There is a small text right under the big logo. "Trang web được phát triển bởi Hội Sinh viên Trường Đại học Kinh tế TP. HCM"
4. There are logos right under the text as mentioned above: UEH logo and Student Association logo
5. There are 2 columns of fact button as the example below:
![image](https://user-images.githubusercontent.com/87629993/126808577-37cfc57c-3026-40c5-aeee-1758481646e8.png)

**Comment by Yen21351** [comment]
@KhaB-BIT 
- The back to top button only appears when the user scrolls to footer
