### ISSUE TITLE
Homepage | Body Part - Unit Organization Logo Banner

### ISSUE THREAD

**Issue by Chammmmmm** [UEH-Squad/VMS#32]
As a user,

I want to know which unit organizations are involved in this website
So that I can know the scope of this website.

**Acceptance Criteria:**
1. A big banner with freestyle design is compulsory to be blue, green and white.
- Position: above the footer
2. @Meenomenal will provide to you all of the logo (including the unit organizations which are directly managed by Department).
3. There are two arrows on the top-right and top-left of the banner directing me to the other logos if the banner is full.

**Comment by Yen21351** [comment]
@ThaiNgocHuuBang 
- All the area logos will be replaced when users click on the arrows
- Endless loop for all the logos
